### ISSUE TITLE
Review 4: AddActivity.jsx & ListOpportunities.jsx

### ISSUE THREAD

**Issue by silviadebenedictis** [team-four-ics414/voluntree#77]
## Overview

The focus for this code review will be centered around the AddActivity and ListOpportunities pages. 
Please pay attention too:
* Javascript issues
* React components

## Review Branch

review-04

## Files to review

* AddActivity.jsx
* ListOpportunities.jsx

## Checklists

* [Architecture](../../checklists/architecture-checklist.md)
* [Design](../../checklists/design-checklist.md)
* [JS](../../checklists/js-checklist.md)
* [React](../../checklists/react-checklist.md)
* [Testing](../../checklists/testing-checklist.md)

## Due date

19th, February 11:30pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by silviadebenedictis** [comment]
### AddActivity.jsx

- JS-01: Consider turning the frequency field into a list with predefined options like "Daily," "Weekly," and "Monthly" 

### ListOpportunities.jsx

- Design-09: Component handles both UI rendering and filtering logic. The filtering logic could be put into separate functions for better code organization and reusability.

**Comment by joelvanta** [comment]
### AddActivity.jsx
JS-01: details, benefits, requirements can be combined into a single’ description’ of the activity.

### ListOpportunities.jsx
JS-01: Add ‘Others’ category for unspecified category.

**Comment by mikhail-shkaralevich** [comment]
### AddActivity.jsx

**Comment by mnakagawa14** [comment]
### ListOpportunites.jsx

Might be better to have 'All Categories' instead of ' ' in the Dropdown.Menu

### AddActivity.jsx

Should requirement be a single String? Would it be better to have an array of Strings. That way we could separate different requirments.
